---
- name: Revert VM
  hosts:
    - hyper_v
  tasks:
    - name: Revet vms to the last snapshot
      hyper_v_vm_snapshots:
        name: '*TMP*'
        state: create
        snapshotname: 'start exercise'